name: Production CI/CD

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:

      # =========================
      # CHECKOUT CODE
      # =========================
      - name: Checkout Repository
        uses: actions/checkout@v4

      # =========================
      # LOGIN TO DOCKER HUB
      # =========================
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # =========================
      # BUILD BACKEND IMAGE
      # =========================
      - name: Build Backend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my_api_project-backend:latest .

      # =========================
      # PUSH BACKEND IMAGE
      # =========================
      - name: Push Backend Docker Image
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/my_api_project-backend:latest

      # =========================
      # BUILD WORKER IMAGE
      # =========================
      - name: Build Worker Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my_api_project-worker:latest .

      # =========================
      # PUSH WORKER IMAGE
      # =========================
      - name: Push Worker Docker Image
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/my_api_project-worker:latest